### ISSUE TITLE
Missing “acra/examples/python” directory 

### ISSUE THREAD

**Issue by cr0hn** [cossacklabs/acra-engineering-demo#54]
This is referenced in many places, but it’s not in repo

**Comment by Lagovas** [comment]
It is repository cloned by commands like `curl https://raw.githubusercontent.com/cossacklabs/acra-engineering-demo/master/run.sh |  bash -s -- python-mysql`. Referenced [run.sh](https://github.com/cossacklabs/acra-engineering-demo/blob/master/run.sh#L496) clones https://github.com/cossacklabs/acra repository to the current directory and further steps rely on this.
